### ISSUE TITLE
As a user I should be able to select more than one tag at the same time. 

### ISSUE THREAD

**Issue by jai-dewani** [markodenic/awesome-tech-blogs#128]
Suppose a user want's to checkout all the blogs with `C#` and `Cloud` tag. At this moment there is no support from the website to do so. 

There are two routes we can take from here. Selecting two tags A and B shows all blogs which have `A and B` i.e. both tags or `A or B` i.e. any one of them. A possible solution to this could be to allow users to select between `and`/`or` functionality but I would rather prefer it to have `A and B` by default, a personal preference. 

What's your opinion on this @markodenic?

**Comment by markodenic** [comment]
Let's keep it simple. I'll add it to the backlog, and think about it later. 

Thanks for the suggestion.
