### ISSUE TITLE
GitHub workflow for formatting JSON data

### ISSUE THREAD

**Issue by jai-dewani** [markodenic/awesome-tech-blogs#131]
I noticed that some of the entries in the `data.js` aren't very well formatted. We should be able to easily add a JSON formatter in our GitHub action workflow to solve this issue. 

Not doing this does not affects anything, I just prefer having well formatted JSON. Especially if it's long list of nested JSON xD

**Comment by markodenic** [comment]
Hey, @jai-dewani. Great idea. Can you make a PR?

**Comment by version0chiro** [comment]
hey @markodenic I have submitted a PR that deals with this issue #136 using workflow of GitHub

**Comment by jai-dewani** [comment]
Thanks for the PR @version0chiro, It looks good to me. Let's see what @markodenic has to say

**Comment by version0chiro** [comment]
I think we can close this issue now?

**Comment by markodenic** [comment]
Fixed in #135. Thanks, Sachin.
