### ISSUE TITLE
Duplicate tags

### ISSUE THREAD

**Issue by naresh-io** [markodenic/awesome-tech-blogs#184]
Duplicate tags are being listed due to case sensitivity

**Example:** Right now `JavaScript`, `javascript`, `Javascript` are being considered as 3 different tags.

Reference 👇

![image](https://user-images.githubusercontent.com/20286571/147904813-135de54d-d736-4746-859a-c825dfc78e99.png)

**Comment by Timonwa** [comment]
Is this issue assigned to someone already? Can I handle it?

**Comment by naresh-io** [comment]
I've already raised a PR, it's under review #185

**Comment by Timonwa** [comment]
Ok. Cool.

**Comment by markodenic** [comment]
Hey, @naresh-io. We'll leave this as it is for now.
