### ISSUE TITLE
Issue with PR

### ISSUE THREAD

**Issue by CBID2** [markodenic/awesome-tech-blogs#394]
Hi @markodenic! I created a [PR](https://github.com/markodenic/awesome-tech-blogs/pull/393) to add my blog to your repo, and it's not working for some reason. Can you help me?

**Comment by markodenic** [comment]
@CBID2 It was not your fault. We were just busy. Merged! https://github.com/markodenic/awesome-tech-blogs/pull/393

**Comment by CBID2** [comment]
> @CBID2 It was not your fault. We were just busy. Merged! https://github.com/markodenic/awesome-tech-blogs/pull/393

Thanks for clarifying
