### ISSUE TITLE
GitHub Action Issue 

### ISSUE THREAD

**Issue by CBID2** [markodenic/awesome-tech-blogs#406]
Hi @miohtama! I made this [PR](https://github.com/markodenic/awesome-tech-blogs/pull/405) today, and notice that the Node Code formatter gave it an error. Upon further investigation, a colleague and I found that [the action flow for merging PRs is broken](https://github.com/markodenic/awesome-tech-blogs/actions/workflows/AutoFormatter.yml). Can you fix it?

**Comment by markodenic** [comment]
Hey @CBID2. Thanks for raising this issue. I removed the Action for the moment. When I have more time I'll add a new one.

**Comment by CBID2** [comment]
Ok
