### ISSUE TITLE
Add count of the number of people in a tag

### ISSUE THREAD

**Issue by jai-dewani** [MarkoDenic/awesome-tech-blogs#78]
I saw this feature on [`/uses`](https://uses.tech/). Link to the repo [`wesbos/awesome-uses`](https://github.com/wesbos/awesome-uses)

![image](https://user-images.githubusercontent.com/33520257/110198541-578e0580-7e79-11eb-8144-3fe72e54dde9.png)

**Comment by MarkoDenic** [comment]
Feature added in https://github.com/MarkoDenic/awesome-tech-blogs/pull/79
